[Poll_Settings]
poll_interval_in_secs = 300

[Json_Sender_Logger]
use = true
min_interval_in_secs = 5
address_in = "http://molgpu01.mit.edu:8088"
auth_code = "lab_cluster_2025"

[Google_Sheets_Logger]
use = false

[StdOut_Logger]
use = false


